config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "boards" => "boards#index", as: :boards
  get "boards/new" => "boards#new", as: :new_board
  get "boards/:id" => "boards#show", as: :board
  post "boards" => "boards#create"

  root "boards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  serialize :data, type: Array, coder: YAML
  validates :name, presence: true, uniqueness: true
  validates :column, :row, numericality: { only_integer: true, greater_than: 1 }
  validates :mines_count, numericality: { only_integer: true, greater_than: 0 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def generate!
    initialize_board
    set_mines
  end

  private

  def initialize_board
    self.data = Array.new(row) { Array.new(column, 0) }
  end

  def set_mines
    mines_placed = 0

    while mines_placed < mines_count
      r_row = rand(row)
      r_column = rand(column)

      if data[r_row][r_column] == 0
        data[r_row][r_column] = 1
        mines_placed += 1
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]

  def index
    @boards = if params[:view_all]
                Board.all.order(created_at: :desc)
              else
                Board.order(created_at: :desc).limit(10)
              end
  end

  def show; end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.generate!

    if @board.save!
      redirect_to @board
      flash[:success] = "Board #{@board.name} was successfully created."
    else
      render :new
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board)
          .permit(:name, 
                  :row, 
                  :column, 
                  :mines_count, 
                  :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.slim
.d-flex.justify-content-between.align-items-center
  h4 style="margin: 0" #{board.name}

.d-flex
  small.card-subtitle style="margin-right: 1rem;"
    | by #{board.email}
  small.card-subtitle.text-body-secondary
    = "#{board&.created_at&.to_date}"
.card-text
  p row #{board.row}
  p column #{board.column}
  p mines_count #{board.mines_count}
  p board

  .container.mt-4
    table.table.table-bordered
      thead
        tr
          th scope="col" style="width: 50px; height: 50px" #
          - board.column.times do |i|
            th scope="col" style="width: 50px; height: 50px" = i+1
      tbody
        - board.data.each_with_index do |row, index|
          tr
            th scope="row" = index+1
            - row.each do |cell| 
              
              td class="#{cell == 1 ? 'table-danger' : 'table-light'}" style="width: 50px; height: 50px"
                = cell == 1 ? '💣' : ' '

div style="float: right"
  = link_to "List of Boards", boards_path, class: 'btn btn-outline-secondary', style: "margin-right: 1em"

app/views/boards/_form.slim
.row.d-flex.justify-content-center
  .col-md-6.col-lg-5
    = render 'layouts/error_message', data: board

    = form_with(model: board, data: { turbo: false }) do |f|
      = f.label :email, class: 'form-label'
      = f.text_field :email, class: "form-control mb-2 border border-primary-subtle"
      = f.label :board_name, class: 'form-label'
      = f.text_field :name, class: "form-control mb-2 border border-primary-subtle"
      = f.label :column, class: 'form-label'
      = f.number_field :column, value:"2", class: "form-control mb-2 border border-primary-subtle"
      = f.label :row, class: 'form-label'
      = f.number_field :row, value:"2", class: "form-control mb-2 border border-primary-subtle"
      = f.label :total_mines_count, class: 'form-label'
      = f.number_field :mines_count, value:"1", class: "form-control mb-2 border border-primary-subtle"

      div style="float: right"
        = link_to "Cancel", board, class: 'btn btn-outline-secondary', style: "margin-right: 1em"
        = f.submit "Save", class: 'btn btn-primary'

app/views/boards/index.slim
#boards.container-fluid
  .row.d-flex.justify-content-center
    .col-md-6.col-lg-5.col-xl-4
      - if @boards.present?
        = link_to "Create", new_board_path, class: "board", class: 'btn btn-secondary'

        - @boards.each do |board|
          .card.mb-3
            .card-header
                h5.card-title
                  = link_to "#{board.name}", board, class: "board"

            .card-body
              h6.card-subtitle.mb-2.text-body-secondary
                | by #{board.email}
              p.card-text 
                = board.created_at.strftime("%B %d, %Y")
      - else
        .card.mb-3
          .card-body
            p.card-text 
              | No boards yet. 
              = link_to "Create one now!", new_board_path, class: "board"
      
      - if params[:view_all]
        = link_to 'View Most Recent 10', boards_path, class: 'btn btn-primary'
      - else
        = link_to 'View All Boards', boards_path(view_all: true), class: 'btn btn-primary'

app/views/boards/new.slim
.container-fluid
  = render "form", board: @board

app/views/boards/show.slim
.container-fluid
  .row.d-flex.justify-content-center
    .col-md-6.col-lg-5
      = render @board

app/views/layouts/_error_message.slim
- if data&.errors&.any?
  .alert.alert-dismissible.fade.show class="alert-danger" role="alert"
    h6 
      | Unable to continue due to the following error(s).
    ul
      - data.errors.each do |error|
        li = error.full_message

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyMineSweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>